#!/usr/bin/env bash
set -euo pipefail

if [[ "$#" -lt 1 || -z "$1" ]]; then
	crystal spec
else
	if [[ "${1}" == *_spec.cr ]]; then
		crystal spec "${1}"
	else
		candidate="spec/${1#*/}"
		candidate="${candidate%.cr}_spec.cr"

		if [[ -f "${candidate}" ]]; then
			crystal spec "${candidate}"
		else
			echo >&2 "${1} is not a spec file and no spec candidate was found."
			exit 1
		fi
	fi
fi
