#!/usr/bin/env bash
set -euo pipefail

# See https://www.gnu.org/prep/standards/html_node/Errors.html
shards build -q --format=json | tail -n +2 | gojq --raw-output '.[] | .file + ":\(.line):\(.column): \(.message)"'
